local_costmap:
   global_frame: odom
   robot_base_frame: /base_link
   update_frequency: 3.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   always_send_full_costmap: true
   width: 2.0
   height: 2.0
   resolution: 0.05
   transform_tolerance: 0.5
   map_type: costmap
   plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
   inflation_layer:
      inflation_radius: 0.15